### ISSUE TITLE
Breaks `-n test_method_name` feature from Ruby

### ISSUE THREAD

**Issue by leehambley** [turn-project/turn#78]
`require 'turn'` breaks the feature in Ruby where you can do `ruby -Itest ./my_test.rb -n test_just_this_one_thing`.

Under the defaults, this would run only the method named `test_just_this_one_thing`, with `turn` loaded, however it runs all tests, all the time.

The ruby docuemntation for this feature is misleading, or I'm misunderstanding it:

```
ruby --help
... snip ...
  -n              assume 'while gets(); ... end' loop around your script
... snip ...
```

A note further to this is that when using bundler, turn appears to be badly behaved:

``` ruby
gem 'turn', :require => false
```

should make bundler skip loading this, but it doesn't - turn still loads, even if I do not explicitly require it anywhere. (it's possible, something in Rails is auto-loading it, but I really hope not.

**Comment by trans** [comment]
Interesting, I've never read anything about using -n in this way before. I'll need to understand more about this in order to address. Does MiniTest normally detect the `-n` option and adjust for it? Not sure how it happens. Also not sure how Turn would interfere with it b/c turn is little more than a plugin test formatter for MiniTest. So any more info on this you can provide would be a big help.

As for the Bundler issue, that should have been resolved with the lasted release. I've tried it here and have no issue. So a couple things to check.
- Uninstall all old versions of Turn, only have the latest installed.
- If using require method of running with turn, use `require 'turn/autorun'`, not `require 'turn'`.

**Comment by leehambley** [comment]
@trans, thanks for the info. I'm actually totally unsure about the `-n` option, I had always assumed it was a Ruby option, but never bothered to look at the documentation. When I needed it last week, I tried it out and it hadn't worked. I'll see if I can create a test-case, it's not something that integrates with unit tests, I fear.

My guess regarding _does minitest detect and adjust for `-n`_ would first be _does argv contain anything after Ruby is done reading it's options?_, (thus would that even be possible), and … ~~knowing~~ almost understanding how the test runner and IO streams are integrated I could imagine that it's possible to skip resolving the test result unless it matches?

Re `bundler`, good to know, if I do have problems with the latest version, I'll take a look.

**Comment by trans** [comment]
Ok. I'll play with `-n` when I get a chance and see what I can figure too.

Note, that I mistyped, `turn/autotest` should be `turn/autorun`.

**Comment by leehambley** [comment]
> If using require method of running with turn, use require 'turn/autorun', not require 'turn'.

Ok, cool - I've tried both, with whatever's installed on my system (cant' tell right now, as I'm at the office) - it did't make any difference, but I'll clean-up, and give a real try today.

I also feel quite certain that the `-n` documentation for Ruby is wrong, I can't see how a `while gets()` being implied around the script would cause behaviour like any of that.

**Comment by trans** [comment]
I tried out `-n` option and it does get passed through to ARGV. Then I looked at MiniTest code and it does parse for `-n`.  I just pushed a change to Turn that takes this into account.

**Comment by leehambley** [comment]
@trans Cheers, I'll grab HEAD and try it out when I get home this evening, have a good day.

**Comment by enwood** [comment]
I'm noticing that 'turn' 0.8.3 still interferes with both the ability of both the 'polyamory' gem and the 'm' gem to run a single test identified by line number. When turn is loaded, neither of these two gems will run a single test at a specific line. (e.g.  $m test/controllers/packages_controller_test.rb:30 or polyamory -Itest test/controllers/packages_controller_test.rb:30). All tests in the specified file end up being run. 

If turn is removed from the Gemfile, then both m and polyamory will run only the test at the specified line number.

**Comment by whatbird** [comment]
i'm still seeing this (turn 0.9.6). i use -n all the time in my flow, and it stopped working when i installed turn

FYI: i'm not using polyamory or m. am using minitest (4.7.5), rails (3.2.15)
